### PR TITLE
Change logo colors to match site.

### PR DESCRIPTION
**Pull request by kfarr2**
Client will need to supply original, high quality logo if they would like this change to be implemented.

### CODE REVIEW

**Comment by wylee** [comment]
Can we close this or does it need to be reviewed?

**Comment by kfarr2** [comment]
We should probably just close it. It's been sitting here for a while.
> closing...

**Comment by kfarr2** [comment]
Reopened because the client asked for this in her most recent email

**Comment by kfarr2** [comment]
Gonna do this in a different PR

**Pull request closed without merging**
