### PR TITLE
Use PIL instead of ImageMagick for *all* image operations

### PR DESCRIPTION
**Pull request by kfarr2**
I would use `resize()` but `thumbnail()` calculates the aspect ratio and calls `resize()` for us anyway.

### CODE REVIEW

**Comment by wylee** [comment]
The resize_image commits should be as follows:

- Rename utils.resize_image to generate_thumbnail (w/ further text explaining why)
- Reimplement utils.generate_thumbnail using PIL (w/ further text explaining why)

Currently, the two commits overlap in that the second one does the renaming while also fixing your original reimplementation.

Ideally, these commits would be one after the other in the git history instead of having an unrelated commit in between.

In addition, it would be good to start adding `OIH-NNN` at the bottom of commit messages so your commits will be linked to issues in JIRA.

**Comment by kfarr2** [comment]
This should be ready to merge.

**Comment by wylee** [comment]
- The commit messages for both commits aren't formatted according to standards
- `utils.resize_image` should be renamed first and then re-implemented
- The docstring for `generate_thumbnail` was copied verbatim from an inline comment on an earlier version of the commit; it still says "blah dee blah dee blah"
- `import os, sys` should be two imports
- Stdlib imports should be alphabetized
- There should be a blank line after stdlib imports and other imports
- A small, simple function like `generate_thumbnail` doesn't need any blank lines
- In `generate_thumbnail`, you should try the open in a different block from where you try the save; that way, you can catch different types of errors and log them appropriately

**Comment by kfarr2** [comment]
How's this?

**Comment by ssean1** [comment]
The commits aren't showing up in JIRA -- I think it's because of the extra indentation in the commit's body. Try unindenting that and it *should* work.

I've rebased these changes onto a test branch, and icons appear to be displaying correctly. This PR looks good to me.

**Comment by wylee** [comment]
@ssean1 Are you sure you don't see any issues at all with this PR?

**Comment by ssean1** [comment]
@wylee that makes sense, they aren't showing up in Jira at the moment but that would explain why.
I don't see any issues with it -- I tried creating a few reports in different locations with different images, species, etc.

**Comment by wylee** [comment]
Take another look at the second commit. The code may work, but there could still be other issues.

**Comment by ssean1** [comment]
@wylee Is it how the input filepath is constructed from the output path?

**Comment by wylee** [comment]
Yes, it has to do with logging. The title of the commit is "rename something...", but it's also doing other stuff that belongs in a different commit.

**Comment by ssean1** [comment]
@wylee, @kfarr2 Some of the import statements, as well as instantiating the logger, look like they can be moved to a different commit or described in the commit message. Would it be better to append a line to the commit's body describing the purpose of adding the logger though?

**Comment by wylee** [comment]
It would be better to move the unused imports and logger into the commit where they're used.

**Comment by ssean1** [comment]
OH I see what's going on -- importing the logger and instantiating it, as well as importing `PIL.image`, can be moved to 7efdc90

**Comment by kfarr2** [comment]
fixed.

**Comment by wylee** [comment]
I cherry-picked the `resize_image`/`generate_thumbnail` commits into develop.

The `Report.generate_icon` may need a little more work. It might just be an aesthetic thing, but I'm not a fan of CAP_VAR_NAMES inside a method.

**Comment by kfarr2** [comment]
I was always taught to use all caps for constants & magic numbers. Granted, that was C++, and these aren't global-level constants, but it doesn't violate pep8 and I thought it might be easier to refactor later (into settings, or some enum file) if they're all caps. If it's really an issue though, I'll change it.

Aside from that, all that needs to be done is to rebase this PR to get rid of `5c10e17` & `3fbb41c`, correct?

**Comment by wylee** [comment]
I've never heard of CAPS names being recommended inside a function, and I'd argue that it at least violates the _spirit_ of PEP8.

Regardless, the main issue is that `Report.generate_icon` is a bit unwieldy in general and perhaps doesn't belong in the model at all.

Since we are refactoring this to make things cleaner in general, it makes more sense to me to clean it up now rather than plan to re-refactor it later.

If I was working on this, I'd probably do this (roughly):

- Create a new module called `report.utils`
- Move the `generate_icon` method there as a function
- Add `icon` and `color` args
- Instead of "magic numbers", add keyword args to the function
- Add a new `Report.icon` property that calls the new `generate_icon` function if the icon doesn't already exist

**Comment by kfarr2** [comment]
Alright. That ought to do it.

**Comment by kfarr2** [comment]
Fixed.

**Comment by kfarr2** [comment]
How exactly is that better?
 
Reports are initialized in the create view, where there isn't a species or category yet specified. So this would result in an empty icon being created or specified. Doing it on `__init__()` would also mean that code gets run every time the object is accessed. So every time a user updates a report, `__init__()` is called twice (when it is saved on submit, and when it is loaded on redirect).

[Django docs](https://docs.djangoproject.com/en/1.9/ref/models/instances/#creating-objects) also advise against overriding `__init__()` and say to either override a class method or make a custom manager instead. Why not just override the `save()` method? 

Even then, when a report is saved the user is automatically redirected to the detail view, and the only icon loaded on that page is the one corresponding to that report. So the icon check is essentially done just after the object is saved anyway. And since there can be multiple reports to each icon, saving a report doesn't necessarily entail creating a new icon. 

Even if the icon is generated on save instead of when the icon path is accessed, we would still need to check that the icon path exists and generate it if it doesn't. (What would happen if all the icon files got deleted somehow?)

TBH I don't see the advantage in doing this and I think refactoring this adds unnecessary complexity to the project.

**Comment by wylee** [comment]
The idea behind creating the icon on init  is to ensure the object is fully initialized. Conceptually this makes sense to me. It would also ensure the icon exists when the report is accessed in case, as you say, it got deleted somehow. I'm not worried about the check running twice in two different requests, because the effect of that on performance is negligible.

I don't necessarily agree with what the Django docs say about overriding a model's `__init__` method, but that's irrelevant, because we can just use a `post_init` handler instead.

Generally, it's not a good idea to create something as a side effect of accessing a property. I found the original implementation confusing in this regard. Creating the icon on save or init is conceptually simpler and less surprising, which is objectively better.

Also, what happens if you want to generate the icon for a report (or group of reports) in some other context? You'd have to do something silly like call `report.icon_url` to create the icon even though you don't need the URL. You could argue that this we'll never need to do that in this project, but I don't think that's a good rationale for not making the code as clean as possible.

I can't see how this change would make anything _more_ complex. It would add a few lines of code to make things easier to understand for the next person who comes along. It will also take very little time to make this change, so it seems beneficial to me.

**Comment by kfarr2** [comment]
Except that `__init__` is called when the user navigates to `reports/create` which initializes the model instance for the form which has no data to build an icon with. The icon has to be generated which means we either need to define a default value, or handle the errors. (Thereby adding more paths to the source code aka increasing complexity by definition).

And no, they would just call `utils.generate_icon`. Was that not the reason for refactoring all that code in the first place?

**Comment by wylee** [comment]
You could do a really simple check to say "if the report is new, don't create the icon". That would be one extra conditional, not a bunch of paths and complexity and what not.

Regardless, this doesn't have to be done in `__init__` if there's a better way. All the discussion around that is sort of beside the point, which is that the current version does initialization via side effects, which is generally frowned upon and easy to fix in this case.

If you had a list of `Report` instances and wanted to generate icons for them, you would preferably call `Report.generate_icon`.

The main reason for the _refactoring_ was to get rid of the ImageMagick dependency and make the code maintainable. The reason for _moving_ the icon generation code into `utils` was to keep the main body of the `Report` model from being too unwieldy and also to make testing of icon generation easier.

**Comment by wylee** [comment]
What do you think about this implementation?:

```diff
diff --git a/hotline/reports/models.py b/hotline/reports/models.py
index b7656f8..07b10a6 100644
--- a/hotline/reports/models.py
+++ b/hotline/reports/models.py
@@ -11,6 +11,8 @@ from django.contrib.auth import get_user_model
 from django.contrib.gis.db import models
 from django.core.mail import send_mail
 from django.core.urlresolvers import reverse
+from django.db.models.signals import post_init
+from django.dispatch import receiver
 from django.template import Context
 from django.template.loader import get_template, render_to_string

@@ -132,14 +134,12 @@ class Report(models.Model):
         ``static/js/main.js`` also.

         """
-        if not os.path.exists(self.icon_path):
-            generate_icon(
-                    self.category.icon,
-                    self.icon_color,
-                    self.icon_path,
-            )
         return posixpath.join(settings.MEDIA_URL, self.icon_rel_path)

+    def generate_icon(self):
+        if not os.path.exists(self.icon_path):
+            generate_icon(self.category.icon, self.icon_color, self.icon_path)
+
     @property
     def image_url(self):
         """
@@ -179,6 +179,12 @@ class Report(models.Model):
         return bool(self.reported_species and self.actual_species and self.reported_species != self.actual_species)


+@receiver(post_init, sender=Report)
+def post_init__generate_icon(sender, instance, **kwargs):
+    if instance.pk is not None:
+        instance.generate_icon()
+
+
 class Invite(models.Model):
     """
     Abitrary people can be invited (via email) to leave comments on a report
```

**Pull request closed without merging**
