### PR TITLE
Switch from varlet to django-local-settings

### PR DESCRIPTION
**Pull request by kfarr2**
Refactor from varlet to django-local-settings.

### CODE REVIEW

**Comment by wylee** [comment]
This is looking pretty good. Do you think you could get the tests passing on Travis too? I.e., update .travis.yml to use local settings. vcp and team_dynamics are good examples of how to do this.

**Comment by kfarr2** [comment]
I was just working on figuring this out and I think those were just the hints I needed. lol. Thanks.

**Comment by wylee** [comment]
If you squash this all into a single commit with the subject "Switch from varlet to django-local-settings (standardization)", I think we can call it good.

**Comment by wylee** [comment]
I changed the name of this PR because switching to the new deployment tool/task runner will be a separate PR.

**Pull request merged**
