### PR TITLE
Fix/ui

### PR DESCRIPTION
**Pull request by kfarr2**
Add cancel buttons to forms
Add delete buttons & view to comments
Update logo & favicon to reflect clients request.

### CODE REVIEW

**Comment by kfarr2** [comment]
Don't merge this just yet. I just noticed an issue with the colors in the logo that I am fixing right now.

**Comment by wylee** [comment]
I manually merged the commits changing the favicon and logo colors. The other two will need to be rebased on current develop w/ whatever amendments are necessary.

**Comment by kfarr2** [comment]
Alright. So the code has been refactored slightly. 
The cancel button on the `edit.html` page now uses a link, and has been moved (along with all other related code) to the `_edit.html` page. Some javascript is left to handle the sliding animation that occurs when a new comment is added to the `reports/detail.html` page.
Also the permission `can_delete_comment()` has been created and added to the `perms.py` file. It is somewhat redundant to check this permission though, as the cases will only ever be

* user creates a new comment, which wouldn't have a primary key *or*
* user edits a comment. In which case permission checking is done before they can view the page.

However, it does help readability to have it in there.

**Comment by wylee** [comment]
I thought we already did the `STATIC_URL` => `static` conversion (it looks like you did that in 6bda827).

The commits "Update favicon colors" and "Replace old hotline logo with new one" have already been merged.

**Comment by kfarr2** [comment]
I think my previous comment was deleted when I cherry-picked out the old commits.
The `get_redirect_location()` function is not available in the version of arcutils used for this project. 
I'm unsure how to proceed with the cancel buttons.

**Comment by wylee** [comment]
I'm not sure that upgrading this project to arcutils v2 is feasible right now... although it could be, depending on how much of arcutils is actually being used. If you think it's doable without too much effort, I think that it would be a really good idea.

Even if this project _was_ using arcutils v2, [the method I linked to](https://github.com/PSU-OIT-ARC/django-arcutils/blob/develop/arcutils/masquerade/views.py#L32) is buried in the masquerade app, so it wouldn't be usable anyway (at least, not without hackery). I'm thinking that it might be useful to extract that method into a generic function in arcutils (in fact, I'll probably do that in a minute).

For now, I think it's probably best to stick with the hard coded links and work on higher priority stuff.

**Comment by wylee** [comment]
Would it be possible to combine the two cancel-button commits?

**Comment by wylee** [comment]
I cherry-picked 13ae5e1 ("Change link for 'Admin' to 'Species' for managers") into develop.

The other three commits overlap and should be edited into the following two logical commits:

* Add cancel buttons
* Make comments deletable (you can split this into back/front end commits if you want, but I don't think that's necessary)

**Comment by kfarr2** [comment]
Should I remove the cherry-picked commit?

**Comment by wylee** [comment]
Yes, this PR should include only the "make comments deletable" and "add cancel buttons" commits. Those two commits still overlap, though, which is why they still haven't been merged.

**Comment by wylee** [comment]
I cherry-picked these into develop and made a few tweaks.

**Pull request closed without merging**
