### PR TITLE
Update/arctasks

### PR DESCRIPTION
**Pull request by kfarr2**
Get base site running with arctasks.

### CODE REVIEW

**Comment by kfarr2** [comment]
I've gotta go to class but I'll work more on this today if I get a chance.

**Comment by wylee** [comment]
Would it be possible to squash this into just one or two commits? It seems to me that there's one commit for fixing the convert script and there's another for switching to arctasks.

**Comment by kfarr2** [comment]
I was planning on rebasing them all into one or two commits once I get the tests to pass.

**Comment by wylee** [comment]
See d7844e57c803ff7bb012243851d550d2ae74e16a to 347c31f27c720f24b13e05e0652301ad240aed12

**Pull request closed without merging**
